####################################################################################
# Nexys4 Demo Board Constraint File
####################################################################################

# System Clock (100 MHz)
# ----------------------
create_clock -name CLK_I -period 10.000 [get_ports CLK_I]

# Clock and Reset
# ---------------
set_property PACKAGE_PIN E3       [get_ports CLK_I]
set_property PACKAGE_PIN C12      [get_ports RSTN_I]

set_property IOSTANDARD LVCMOS33  [get_ports CLK_I]
set_property IOSTANDARD LVCMOS33  [get_ports RSTN_I]

# Pushbuttons (uncomment if used)
# -------------------------------
# set_property PACKAGE_PIN T16      [get_ports BTNL_I]
# set_property PACKAGE_PIN E16      [get_ports BTNC_I]
# set_property PACKAGE_PIN R10      [get_ports BTNR_I]
# set_property PACKAGE_PIN V10      [get_ports BTND_I]
# set_property PACKAGE_PIN F15      [get_ports BTNU_I]
# 
# set_property IOSTANDARD LVCMOS33  [get_ports BTNL_I]
# set_property IOSTANDARD LVCMOS33  [get_ports BTNC_I]
# set_property IOSTANDARD LVCMOS33  [get_ports BTNR_I]
# set_property IOSTANDARD LVCMOS33  [get_ports BTND_I]
# set_property IOSTANDARD LVCMOS33  [get_ports BTNU_I]

# Switches (uncomment if used)
# ----------------------------
set_property PACKAGE_PIN U9       [get_ports {SW_I[0]}]
set_property PACKAGE_PIN U8       [get_ports {SW_I[1]}]
set_property PACKAGE_PIN R7       [get_ports {SW_I[2]}]
set_property PACKAGE_PIN R6       [get_ports {SW_I[3]}]
set_property PACKAGE_PIN R5       [get_ports {SW_I[4]}]
set_property PACKAGE_PIN V7       [get_ports {SW_I[5]}]
set_property PACKAGE_PIN V6       [get_ports {SW_I[6]}]
set_property PACKAGE_PIN V5       [get_ports {SW_I[7]}]
set_property PACKAGE_PIN U4       [get_ports {SW_I[8]}]
set_property PACKAGE_PIN V2       [get_ports {SW_I[9]}]
set_property PACKAGE_PIN U2       [get_ports {SW_I[10]}]
set_property PACKAGE_PIN T3       [get_ports {SW_I[11]}]
set_property PACKAGE_PIN T1       [get_ports {SW_I[12]}]
set_property PACKAGE_PIN R3       [get_ports {SW_I[13]}]
set_property PACKAGE_PIN P3       [get_ports {SW_I[14]}]
set_property PACKAGE_PIN P4       [get_ports {SW_I[15]}]
# 
set_property IOSTANDARD LVCMOS33  [get_ports {SW_I[0]}]
set_property IOSTANDARD LVCMOS33  [get_ports {SW_I[1]}]
set_property IOSTANDARD LVCMOS33  [get_ports {SW_I[2]}]
set_property IOSTANDARD LVCMOS33  [get_ports {SW_I[3]}]
set_property IOSTANDARD LVCMOS33  [get_ports {SW_I[4]}]
set_property IOSTANDARD LVCMOS33  [get_ports {SW_I[5]}]
set_property IOSTANDARD LVCMOS33  [get_ports {SW_I[6]}]
set_property IOSTANDARD LVCMOS33  [get_ports {SW_I[7]}]
set_property IOSTANDARD LVCMOS33  [get_ports {SW_I[8]}]
set_property IOSTANDARD LVCMOS33  [get_ports {SW_I[9]}]
set_property IOSTANDARD LVCMOS33  [get_ports {SW_I[10]}]
set_property IOSTANDARD LVCMOS33  [get_ports {SW_I[11]}]
set_property IOSTANDARD LVCMOS33  [get_ports {SW_I[12]}]
set_property IOSTANDARD LVCMOS33  [get_ports {SW_I[13]}]
set_property IOSTANDARD LVCMOS33  [get_ports {SW_I[14]}]
set_property IOSTANDARD LVCMOS33  [get_ports {SW_I[15]}]

# 8-Digit Seven-Segment Display Segments
# --------------------------------------
set_property PACKAGE_PIN L3       [get_ports {DISP_SEG_O[1]}]
set_property PACKAGE_PIN N1       [get_ports {DISP_SEG_O[2]}]
set_property PACKAGE_PIN L5       [get_ports {DISP_SEG_O[3]}]
set_property PACKAGE_PIN L4       [get_ports {DISP_SEG_O[4]}]
set_property PACKAGE_PIN K3       [get_ports {DISP_SEG_O[5]}]
set_property PACKAGE_PIN M2       [get_ports {DISP_SEG_O[6]}]
set_property PACKAGE_PIN L6       [get_ports {DISP_SEG_O[7]}]
set_property PACKAGE_PIN M4       [get_ports {DISP_SEG_O[8]}]

set_property IOSTANDARD LVCMOS33  [get_ports {DISP_SEG_O[1]}]
set_property IOSTANDARD LVCMOS33  [get_ports {DISP_SEG_O[2]}]
set_property IOSTANDARD LVCMOS33  [get_ports {DISP_SEG_O[3]}]
set_property IOSTANDARD LVCMOS33  [get_ports {DISP_SEG_O[4]}]
set_property IOSTANDARD LVCMOS33  [get_ports {DISP_SEG_O[5]}]
set_property IOSTANDARD LVCMOS33  [get_ports {DISP_SEG_O[6]}]
set_property IOSTANDARD LVCMOS33  [get_ports {DISP_SEG_O[7]}]
set_property IOSTANDARD LVCMOS33  [get_ports {DISP_SEG_O[8]}]

set_property PACKAGE_PIN M1       [get_ports {DISP_AN_O[1]}]
set_property PACKAGE_PIN L1       [get_ports {DISP_AN_O[2]}]
set_property PACKAGE_PIN N4       [get_ports {DISP_AN_O[3]}]
set_property PACKAGE_PIN N2       [get_ports {DISP_AN_O[4]}]
set_property PACKAGE_PIN N5       [get_ports {DISP_AN_O[5]}]
set_property PACKAGE_PIN M3       [get_ports {DISP_AN_O[6]}]
set_property PACKAGE_PIN M6       [get_ports {DISP_AN_O[7]}]
set_property PACKAGE_PIN N6       [get_ports {DISP_AN_O[8]}]

set_property IOSTANDARD LVCMOS33  [get_ports {DISP_AN_O[1]}]
set_property IOSTANDARD LVCMOS33  [get_ports {DISP_AN_O[2]}]
set_property IOSTANDARD LVCMOS33  [get_ports {DISP_AN_O[3]}]
set_property IOSTANDARD LVCMOS33  [get_ports {DISP_AN_O[4]}]
set_property IOSTANDARD LVCMOS33  [get_ports {DISP_AN_O[5]}]
set_property IOSTANDARD LVCMOS33  [get_ports {DISP_AN_O[6]}]
set_property IOSTANDARD LVCMOS33  [get_ports {DISP_AN_O[7]}]
set_property IOSTANDARD LVCMOS33  [get_ports {DISP_AN_O[8]}]

# LEDs
# ----
set_property PACKAGE_PIN T8       [get_ports {LED_O[0]}]
set_property PACKAGE_PIN V9       [get_ports {LED_O[1]}]
set_property PACKAGE_PIN R8       [get_ports {LED_O[2]}]
set_property PACKAGE_PIN T6       [get_ports {LED_O[3]}]
set_property PACKAGE_PIN T5       [get_ports {LED_O[4]}]
set_property PACKAGE_PIN T4       [get_ports {LED_O[5]}]
set_property PACKAGE_PIN U7       [get_ports {LED_O[6]}]
set_property PACKAGE_PIN U6       [get_ports {LED_O[7]}]
set_property PACKAGE_PIN V4       [get_ports {LED_O[8]}]
set_property PACKAGE_PIN U3       [get_ports {LED_O[9]}]
set_property PACKAGE_PIN V1       [get_ports {LED_O[10]}]
set_property PACKAGE_PIN R1       [get_ports {LED_O[11]}]
set_property PACKAGE_PIN P5       [get_ports {LED_O[12]}]
set_property PACKAGE_PIN U1       [get_ports {LED_O[13]}]
set_property PACKAGE_PIN R2       [get_ports {LED_O[14]}]
set_property PACKAGE_PIN P2       [get_ports {LED_O[15]}]

set_property IOSTANDARD LVCMOS33  [get_ports {LED_O[0]}]
set_property IOSTANDARD LVCMOS33  [get_ports {LED_O[1]}]
set_property IOSTANDARD LVCMOS33  [get_ports {LED_O[2]}]
set_property IOSTANDARD LVCMOS33  [get_ports {LED_O[3]}]
set_property IOSTANDARD LVCMOS33  [get_ports {LED_O[4]}]
set_property IOSTANDARD LVCMOS33  [get_ports {LED_O[5]}]
set_property IOSTANDARD LVCMOS33  [get_ports {LED_O[6]}]
set_property IOSTANDARD LVCMOS33  [get_ports {LED_O[7]}]
set_property IOSTANDARD LVCMOS33  [get_ports {LED_O[8]}]
set_property IOSTANDARD LVCMOS33  [get_ports {LED_O[9]}]
set_property IOSTANDARD LVCMOS33  [get_ports {LED_O[10]}]
set_property IOSTANDARD LVCMOS33  [get_ports {LED_O[11]}]
set_property IOSTANDARD LVCMOS33  [get_ports {LED_O[12]}]
set_property IOSTANDARD LVCMOS33  [get_ports {LED_O[13]}]
set_property IOSTANDARD LVCMOS33  [get_ports {LED_O[14]}]
set_property IOSTANDARD LVCMOS33  [get_ports {LED_O[15]}]

# RGB LED Signals (uncomment if used)
# -----------------------------------
set_property PACKAGE_PIN K5       [get_ports RGB1_RED_O]
# set_property PACKAGE_PIN F13      [get_ports RGB1_GREEN_O]
# set_property PACKAGE_PIN F6       [get_ports RGB1_BLUE_O]
set_property PACKAGE_PIN K6       [get_ports RGB2_RED_O]
# set_property PACKAGE_PIN H6       [get_ports RGB2_GREEN_O]
# set_property PACKAGE_PIN L16      [get_ports RGB2_BLUE_O]
# 
set_property IOSTANDARD LVCMOS33  [get_ports RGB1_RED_O]
# set_property IOSTANDARD LVCMOS33  [get_ports RGB1_GREEN_O]
# set_property IOSTANDARD LVCMOS33  [get_ports RGB1_BLUE_O]
set_property IOSTANDARD LVCMOS33  [get_ports RGB2_RED_O]
# set_property IOSTANDARD LVCMOS33  [get_ports RGB2_GREEN_O]
# set_property IOSTANDARD LVCMOS33  [get_ports RGB2_BLUE_O]

# VGA Signals (uncomment if used)
# -------------------------------
# set_property PACKAGE_PIN A3       [get_ports {VGA_RED_O[0]}]
# set_property PACKAGE_PIN B4       [get_ports {VGA_RED_O[1]}]
# set_property PACKAGE_PIN C5       [get_ports {VGA_RED_O[2]}]
# set_property PACKAGE_PIN A4       [get_ports {VGA_RED_O[3]}]
# set_property PACKAGE_PIN B7       [get_ports {VGA_BLUE_O[0]}]
# set_property PACKAGE_PIN C7       [get_ports {VGA_BLUE_O[1]}]
# set_property PACKAGE_PIN D7       [get_ports {VGA_BLUE_O[2]}]
# set_property PACKAGE_PIN D8       [get_ports {VGA_BLUE_O[3]}]
# set_property PACKAGE_PIN C6       [get_ports {VGA_GREEN_O[0]}]
# set_property PACKAGE_PIN A5       [get_ports {VGA_GREEN_O[1]}]
# set_property PACKAGE_PIN B6       [get_ports {VGA_GREEN_O[2]}]
# set_property PACKAGE_PIN A6       [get_ports {VGA_GREEN_O[3]}]
# set_property PACKAGE_PIN B11      [get_ports VGA_HS_O]
# set_property PACKAGE_PIN B12      [get_ports VGA_VS_O]
# 
# set_property IOSTANDARD LVCMOS33  [get_ports {VGA_RED_O[0]}]
# set_property IOSTANDARD LVCMOS33  [get_ports {VGA_RED_O[1]}]
# set_property IOSTANDARD LVCMOS33  [get_ports {VGA_RED_O[2]}]
# set_property IOSTANDARD LVCMOS33  [get_ports {VGA_RED_O[3]}]
# set_property IOSTANDARD LVCMOS33  [get_ports {VGA_BLUE_O[0]}]
# set_property IOSTANDARD LVCMOS33  [get_ports {VGA_BLUE_O[1]}]
# set_property IOSTANDARD LVCMOS33  [get_ports {VGA_BLUE_O[2]}]
# set_property IOSTANDARD LVCMOS33  [get_ports {VGA_BLUE_O[3]}]
# set_property IOSTANDARD LVCMOS33  [get_ports {VGA_GREEN_O[0]}]
# set_property IOSTANDARD LVCMOS33  [get_ports {VGA_GREEN_O[1]}]
# set_property IOSTANDARD LVCMOS33  [get_ports {VGA_GREEN_O[2]}]
# set_property IOSTANDARD LVCMOS33  [get_ports {VGA_GREEN_O[3]}]
# set_property IOSTANDARD LVCMOS33  [get_ports VGA_HS_O]
# set_property IOSTANDARD LVCMOS33  [get_ports VGA_VS_O]
# 
# set_property SLEW FAST            [get_ports {VGA_RED_O[0]}]
# set_property SLEW FAST            [get_ports {VGA_RED_O[1]}]
# set_property SLEW FAST            [get_ports {VGA_RED_O[2]}]
# set_property SLEW FAST            [get_ports {VGA_RED_O[3]}]
# set_property SLEW FAST            [get_ports {VGA_BLUE_O[0]}]
# set_property SLEW FAST            [get_ports {VGA_BLUE_O[1]}]
# set_property SLEW FAST            [get_ports {VGA_BLUE_O[2]}]
# set_property SLEW FAST            [get_ports {VGA_BLUE_O[3]}]
# set_property SLEW FAST            [get_ports {VGA_GREEN_O[0]}]
# set_property SLEW FAST            [get_ports {VGA_GREEN_O[1]}]
# set_property SLEW FAST            [get_ports {VGA_GREEN_O[2]}]
# set_property SLEW FAST            [get_ports {VGA_GREEN_O[3]}]
# set_property SLEW FAST            [get_ports VGA_HS_O]
# set_property SLEW FAST            [get_ports VGA_VS_O]

# ADT7420 Temperature Sensor (uncomment if used)
# ----------------------------------------------
# set_property PACKAGE_PIN F16      [get_ports TMP_SCL]
# set_property PACKAGE_PIN G16      [get_ports TMP_SDA]
# set_property PACKAGE_PIN D14      [get_ports TMP_INT]
# set_property PACKAGE_PIN C14      [get_ports TMP_CT]
# 
# set_property IOSTANDARD LVCMOS33  [get_ports TMP_SCL]
# set_property IOSTANDARD LVCMOS33  [get_ports TMP_SDA]
# set_property IOSTANDARD LVCMOS33  [get_ports TMP_INT]
# set_property IOSTANDARD LVCMOS33  [get_ports TMP_CT]

# ADMP421 Omnidirectional Microphone Signals
# ------------------------------------------
set_property PACKAGE_PIN J5       [get_ports PDM_CLK_O]
set_property PACKAGE_PIN H5       [get_ports PDM_DATA_I]
set_property PACKAGE_PIN F5       [get_ports PDM_LRSEL_O]

set_property IOSTANDARD LVCMOS33  [get_ports PDM_CLK_O]
set_property IOSTANDARD LVCMOS33  [get_ports PDM_DATA_I]
set_property IOSTANDARD LVCMOS33  [get_ports PDM_LRSEL_O]

# Audio Out Signals
# -----------------
set_property PACKAGE_PIN A11      [get_ports PWM_AUDIO_O]
set_property PACKAGE_PIN D12      [get_ports PWM_SDAUDIO_O]

set_property IOSTANDARD LVCMOS33  [get_ports PWM_AUDIO_O]
set_property IOSTANDARD LVCMOS33  [get_ports PWM_SDAUDIO_O]

# ADXL362 Accelerometer SPI Signals
# ---------------------------------
set_property PACKAGE_PIN D15      [get_ports ACL_SCLK]
set_property PACKAGE_PIN C15      [get_ports ACL_CSN]
set_property PACKAGE_PIN B14      [get_ports ACL_MOSI]
set_property PACKAGE_PIN D13      [get_ports ACL_MISO]
set_property PACKAGE_PIN C16      [get_ports ACL_INT1]
set_property PACKAGE_PIN E15      [get_ports ACL_INT2]

set_property IOSTANDARD LVCMOS33  [get_ports ACL_SCLK]
set_property IOSTANDARD LVCMOS33  [get_ports ACL_CSN]
set_property IOSTANDARD LVCMOS33  [get_ports ACL_MOSI]
set_property IOSTANDARD LVCMOS33  [get_ports ACL_MISO]
set_property IOSTANDARD LVCMOS33  [get_ports ACL_INT1]
set_property IOSTANDARD LVCMOS33  [get_ports ACL_INT2]

# PS2 Signals
# -----------
set_property PACKAGE_PIN F4       [get_ports PS2_CLK]
set_property PACKAGE_PIN B2       [get_ports PS2_DATA]

set_property IOSTANDARD LVCMOS33  [get_ports PS2_CLK]
set_property IOSTANDARD LVCMOS33  [get_ports PS2_DATA]

set_property PULLUP true          [get_ports PS2_CLK]
set_property PULLUP true          [get_ports PS2_DATA]

# PSRAM Memory Signals
# --------------------
set_property PACKAGE_PIN J18      [get_ports {MEM_A[0]}]
set_property PACKAGE_PIN H17      [get_ports {MEM_A[1]}]
set_property PACKAGE_PIN H15      [get_ports {MEM_A[2]}]
set_property PACKAGE_PIN J17      [get_ports {MEM_A[3]}]
set_property PACKAGE_PIN H16      [get_ports {MEM_A[4]}]
set_property PACKAGE_PIN K15      [get_ports {MEM_A[5]}]
set_property PACKAGE_PIN K13      [get_ports {MEM_A[6]}]
set_property PACKAGE_PIN N15      [get_ports {MEM_A[7]}]
set_property PACKAGE_PIN V16      [get_ports {MEM_A[8]}]
set_property PACKAGE_PIN U14      [get_ports {MEM_A[9]}]
set_property PACKAGE_PIN V14      [get_ports {MEM_A[10]}]
set_property PACKAGE_PIN V12      [get_ports {MEM_A[11]}]
set_property PACKAGE_PIN P14      [get_ports {MEM_A[12]}]
set_property PACKAGE_PIN U16      [get_ports {MEM_A[13]}]
set_property PACKAGE_PIN R15      [get_ports {MEM_A[14]}]
set_property PACKAGE_PIN N14      [get_ports {MEM_A[15]}]
set_property PACKAGE_PIN N16      [get_ports {MEM_A[16]}]
set_property PACKAGE_PIN M13      [get_ports {MEM_A[17]}]
set_property PACKAGE_PIN V17      [get_ports {MEM_A[18]}]
set_property PACKAGE_PIN U17      [get_ports {MEM_A[19]}]
set_property PACKAGE_PIN T10      [get_ports {MEM_A[20]}]
set_property PACKAGE_PIN M16      [get_ports {MEM_A[21]}]
set_property PACKAGE_PIN U13      [get_ports {MEM_A[22]}]
set_property PACKAGE_PIN R12      [get_ports {MEM_DQ[0]}]
set_property PACKAGE_PIN T11      [get_ports {MEM_DQ[1]}]
set_property PACKAGE_PIN U12      [get_ports {MEM_DQ[2]}]
set_property PACKAGE_PIN R13      [get_ports {MEM_DQ[3]}]
set_property PACKAGE_PIN U18      [get_ports {MEM_DQ[4]}]
set_property PACKAGE_PIN R17      [get_ports {MEM_DQ[5]}]
set_property PACKAGE_PIN T18      [get_ports {MEM_DQ[6]}]
set_property PACKAGE_PIN R18      [get_ports {MEM_DQ[7]}]
set_property PACKAGE_PIN F18      [get_ports {MEM_DQ[8]}]
set_property PACKAGE_PIN G18      [get_ports {MEM_DQ[9]}]
set_property PACKAGE_PIN G17      [get_ports {MEM_DQ[10]}]
set_property PACKAGE_PIN M18      [get_ports {MEM_DQ[11]}]
set_property PACKAGE_PIN M17      [get_ports {MEM_DQ[12]}]
set_property PACKAGE_PIN P18      [get_ports {MEM_DQ[13]}]
set_property PACKAGE_PIN N17      [get_ports {MEM_DQ[14]}]
set_property PACKAGE_PIN P17      [get_ports {MEM_DQ[15]}]
set_property PACKAGE_PIN R11      [get_ports MEM_WEN]
set_property PACKAGE_PIN H14      [get_ports MEM_OEN]
set_property PACKAGE_PIN L18      [get_ports MEM_CEN]
set_property PACKAGE_PIN J13      [get_ports MEM_UB]
set_property PACKAGE_PIN J15      [get_ports MEM_LB]
set_property PACKAGE_PIN T15      [get_ports MEM_CLK]
set_property PACKAGE_PIN T13      [get_ports MEM_ADV]
set_property PACKAGE_PIN J14      [get_ports MEM_CRE]
set_property PACKAGE_PIN T14      [get_ports MEM_WAIT]

set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[0]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[1]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[2]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[3]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[4]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[5]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[6]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[7]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[8]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[9]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[10]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[11]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[12]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[13]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[14]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[15]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[16]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[17]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[18]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[19]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[20]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[21]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_A[22]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_DQ[0]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_DQ[1]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_DQ[2]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_DQ[3]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_DQ[4]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_DQ[5]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_DQ[6]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_DQ[7]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_DQ[8]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_DQ[9]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_DQ[10]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_DQ[11]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_DQ[12]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_DQ[13]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_DQ[14]}]
set_property IOSTANDARD LVCMOS33  [get_ports {MEM_DQ[15]}]
set_property IOSTANDARD LVCMOS33  [get_ports MEM_WEN]
set_property IOSTANDARD LVCMOS33  [get_ports MEM_OEN]
set_property IOSTANDARD LVCMOS33  [get_ports MEM_CEN]
set_property IOSTANDARD LVCMOS33  [get_ports MEM_UB]
set_property IOSTANDARD LVCMOS33  [get_ports MEM_LB]
set_property IOSTANDARD LVCMOS33  [get_ports MEM_CLK]
set_property IOSTANDARD LVCMOS33  [get_ports MEM_ADV]
set_property IOSTANDARD LVCMOS33  [get_ports MEM_CRE]
set_property IOSTANDARD LVCMOS33  [get_ports MEM_WAIT]

# Configuration settings
# ----------------------
set_property CFGBVS VCCO         [current_design]
set_property CONFIG_VOLTAGE 3.3  [current_design]
